### ISSUE TITLE
glamour

### ISSUE THREAD

**Issue by sussman** [dhakajack/trfv#29]
Is this a whole class of bugs waiting to happen?  In the start of R1:

>ask glamour
You can't see any such thing.

>a glamour
Carol isn't here.

>ask about glamour
(addressing Christabell)

"A Glamour be not moor than the outwarde Signe to the Seighted of Werked Magick. In the Case of you, it be raw and avid, the very Stuff taken of Life.

**Comment by dhakajack** [comment]
Two issues - one is carol isn't here -- this is somewhat an issue with the conversational framework and whether you've switched interlocutors (and it's better in some cases that we do not do that procedurally because some scenes use rules related to first conversing, which would be undermined).

More generally, I have narrowed the scope, particularly on subjects that should be talked about only in DAN8. This was the purpose of the spreadsheet.

The hardest part of tuning this game would be tweaking the dialogue, which would require more beta test time that we have
